### ISSUE TITLE
Useless redownloading of replays

### ISSUE THREAD

**Issue by lumiera** [springweblobby/swl-website#50]
Starting a replay through http://zero-k.info/Battles/Detail/.... page will download the replay even if:

1) the replay was downloaded and watched before
2) the replay actually is already present because user was in the original battle and has saved the replay.

Both of these are wasteful.

**Comment by Anarchid** [comment]
Case 2) is not possible because replays are only indexed by filename, and filename contains local timestamp. Even if you are in the same timezone as the server, you'll have 1-2 seconds of difference, which will break name identity; and it's not possible to compare value identity without redownloading.

Case 1) is possibly doable - check if replay file with identical filename already exists, use it if available. The downside of a naive implementation would be possibility of collisions between unrelated local and remote replays, but this could be solved with either a prefix, or a separate storage directory for the downloaded replays.

@db81: do you think ~/.spring/demos/remote sounds evil?

**Comment by lumiera** [comment]
Replay filenames when saved should include an SHA hash of contents then. Knowing a hash of remote file will allow to check if that file is present locally.

**Comment by Anarchid** [comment]
*That* would go either on Spring mantis, or on zkinfo tracker.

**Comment by db81** [comment]
Case 1 shouldn't be a problem because it won't redownload an existing replay, it sends If-Modified-Since if the file is already present. This means the download bar will still be shown but the download will be almost instant. Does this fail for you @lumiera? You can run swl with the ```-debug``` argument and it will log when it uses the existing file for downloads.

Collisions are very unlikely, timestamps in replay names are up to seconds. I guess if you're in the same timezone as the server you run a chance of saving your local replay with the same name as Springie. In this case it'll either use the local one or redownload, no harm done.

I don't think it's worth spending effort on Case 2. Replays rarely go above 1-2 megs. Hashes in filenames are ugly and I don't expect you to convince Spring devs to implement that, especially when posed as a solution to such a minor annoyance.

**Comment by lumiera** [comment]
Strange, I tested and got redownloads before submitting an issue, but now the cached version seems to work indeed.

**Comment by db81** [comment]
Your clock can be behind the server's, giving you a window where the cache check fails if the replay is new.

**Comment by Anarchid** [comment]
It's possible to do case 2 via `~/.spring/demos/downloaded` or some such.
