### ISSUE TITLE
No games will start

### ISSUE THREAD

**Issue by ParzivalX** [springweblobby/swl-website#55]
I can try to start any spring mod, I have downloaded all of the required things (maps, game, etc) and it just says game running.

**Comment by Anarchid** [comment]
Check if spring.exe is currently spinning in your task manager. 
Sometimes new spring versions take a while to create a window while they reindex your entire archive cache.

**Comment by ParzivalX** [comment]
There's always three spring.exe running, but it's always taking up some very very small amount of memory.

**Comment by Anarchid** [comment]
That's exactly what happens when it's archivecaching.

**Comment by Anarchid** [comment]
I seemed to be able to download engine 102 and play a a game using SWL.

**Comment by db81** [comment]
> Actually, it most likely is a ZKL thing because ZK now plays fine on SWL.

**Comment by AppSynergy** [comment]
Same here, and with no spring processes running.

I don't think I've ever seen archive caching on my install, it's always super quick...

**Comment by db81** [comment]
@AppSynergy give us your weblobby.log (there's a button to pastebin it in settings if you wanna use that).

Also check to make sure spring runs if you launch it directly.

**Comment by AppSynergy** [comment]
````
/home/usrname/.spring/engine/100.0/spring --xresolution 1366 --yresolution 768 --write-dir /home/usrname/.spring /home/usrname/.spring/weblobby/script.spring
[WARNING] [2016-07-21 18:32:12] Process spring finished with error code 256
[INFO]    [2016-07-21 18:32:12] Command finished: spring
````

Similarly with spring **102.0, 103.0**.  No issues with **96.0**. I tried these four.

I'm assuming `256` is a generic code, or is that a clue?

**Comment by db81** [comment]
Good catch.

**Comment by AppSynergy** [comment]
So yeah, it's fine if I blank the x and y resolution settings.

Which is weird, since [it looks](https://github.com/springweblobby/swl-website/blob/master/store/Process.js#L145) pretty cut-and-dry, and if indeed these args have been gone for a few years,  I must be the only one who filled entered resolution options! :s 

The values in my `Springsettings.cfg` are ignored also (games always start at exact full-screen anyway, which is great).  Can't find [anything](https://springrts.com/wiki/Changelog) to [confirm](https://springrts.com/wiki/Springsettings.cfg), did Spring devs give up on the docs?

**Comment by AppSynergy** [comment]
Nice
